services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DitIsEchtEenSuperVeiligWachtwoord
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

  corvee:
    build: 
      context: ./Corvee.Backend/
    ports:
      - 80:8080
volumes:
  mysql_data: